import { Release } from "./types";

export const releases: Release[] = [
  {
    version: "2.2.3",
    date: "apr 22, 2026",
    title: "relentless guard & quick split security 🛡️",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "fixed the version guard to use relative paths and cache-busting URLs to guarantee users always get the freshest update.",
      "fixed quick split sharing so your friends can view the beautiful receipt link without being forced to create an account.",
      "fixed 'edit receipt' button on quick splits, prevent it appearing on non owner user.",
    ],
  },
  {
    version: "2.2.2",
    date: "apr 16, 2026",
    title: "the always fresh update 🍃",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "fixed service worker caching that was trapping users on old versions of the app.",
      "added a smart 'version guard' that detects new updates, silently assassinates the old cache, and automatically refreshes the app.",
      "added an automated build script to sync version numbers safely.",
      "added offline screen using modern react hooks to gracefully pause the app and prevent unsyncable changes.",
    ],
  },
  {
    version: "2.2.1",
    date: "apr 16, 2026",
    title: "smart routing & modal polish 🧠",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added a 'smart back button' on trip pages that knows if you came from a shared link or the dashboard, preventing users from getting stuck.",
      "added clickable background backdrops to all modals.",
      "added exception for expense detail page, allowing the page shared to a non-logged in user",
    ],
  },
  {
    version: "2.2",
    date: "apr 16, 2026",
    title: "settlements & polish update 🤝",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "added a native 'share the proof' button inside settlements so you can paste the exact math directly into your group chat.",
      "added native ios/android share sheets to both trip pages and quick split receipts.",
      "added safe-area-inset padding so the bottom nav bar perfectly respects phone bezels.",
      "refined the 'who pays who' section. user now can verify their own tab, reveals exactly what was consumed vs paid.",
      "fixed dashboard filters not persist when you hit the back button, now saved via params.",
      "fixed a math display bug where exact split items now properly show their fractions in expense detail page (e.g., french fries (1/2)).",
    ],
  },
  {
    version: "2.1.1",
    date: "apr 15, 2026",
    title: "receipts bug fix & tab sync 🛠️",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "fixed receipts tab filter bug.",
      "fixed a routing bug in switching between trips and receipts.",
      "added search and sorting filters directly to the receipts tab.",
    ],
  },
  {
    version: "2.1",
    date: "apr 15, 2026",
    title: "quick splits 📸",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "added 'quick split': standalone receipts without needing a full group trip.",
      "refine home dashboard with dedicated tabs for trips and quick receipts.",
      "refine about modal and social links",
      "refine changelog layout",
    ],
  },
  {
    version: "2.0.1",
    date: "apr 15, 2026",
    title: "refined navigation & rich cards ✨",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added a clean bottom app bar.",
      "refine profile menu into a sleek, full-screen bottom sheet modal.",
    ],
  },
  {
    version: "2.0",
    date: "apr 13, 2026",
    title: "receipts & borders 🌍",
    badge: "major",
    badgeColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    features: [
      "added smart multi-currency support with dynamic decimal formatting.",
      "added exportable, high-res, nest-branded receipt images for easy sharing.",
      "fixed the date picker with year navigation and a 'right now' shortcut.",
      "fixed a navigation loop bug when exiting trips.",
    ],
  },
  {
    version: "1.2.3",
    date: "apr 2, 2026",
    title: "cleaning up 🧼",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "refine code-base structure",
      "refine changelog ui, separate static imports.",
    ],
  },
  {
    version: "1.2.2",
    date: "apr 2, 2026",
    title: "small changes 😊",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: ["fix info icon size inconsistency."],
  },
  {
    version: "1.2.1",
    date: "apr 2, 2026",
    title: "crew management & prompt fix 👥",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added rename members feature.",
      "refine the member management into a dedicated popup modal.",
      "fix the receipt scanner prompt to strictly output exact category matches.",
    ],
  },
  {
    version: "1.2",
    date: "mar 31, 2026",
    title: "math & polish 💅",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "added a dedicated in-app changelog page.",
      "added transparent breakdowns for custom adjustments in the detailed ledger.",
      "refine the about screen with new social buttons.",
      "fixed a 'phantom tax' math bug for weighted item splits.",
      "fixed some price ui alignment across the board to snap cleanly to the right edge.",
    ],
  },
  {
    version: "1.1",
    date: "mar 31, 2026",
    title: "receipts & ledgers ✨",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "added new receipt scanning logic to handle specific item discounts.",
      "added logic to isolate individual item discounts from global tax and discount math.",
      "added individual item prices directly inside the detailed ledger section.",
      "added transparent item breakdowns associated with each member in the expense list.",
    ],
  },
  {
    version: "1.0.1",
    date: "mar 31, 2026",
    title: "bug fixing 🐛",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added a shiny new about screen with creator social links.",
      "fixed a buggy bouncing arrow on the home screen empty state.",
      "fixed an issue where the about screen wouldn't show when a trip was empty.",
    ],
  },
  {
    version: "1.0",
    date: "mar 31, 2026",
    title: "the beginning 🐣",
    badge: "launch",
    badgeColor: "bg-amber-100 text-amber-700 border-amber-200",
    features: [
      "launched 'nest.' into the wild!",
      "receipt scanning with gemini!",
      "exact splitting, equal splitting, and custom adjustments.",
      "smart debt optimization (who pays who).",
      "beautiful, transparent ledger breakdowns.",
    ],
  },
];
