import { Release } from "./types";

export const releases: Release[] = [
  // 3.0 is a MAJOR release with two halves: (1) merge receipts, and (2)
  // responsive desktop design. Both shipped jul 14, 2026.
  {
    version: "3.0",
    date: "jul 14, 2026",
    title: "desktop + merge receipts 🖥️",
    badge: "major",
    badgeColor: "bg-amber-100 text-amber-700 border-amber-200",
    features: [
      "added a full desktop experience — on bigger screens nest trades the phone-style bottom bar for a persistent sidebar, so trips, receipts, and creating anything new are always one click away.",
      "added a two-column trip dashboard for desktop: the trip summary, members, and settlement ledger sit beside the expense feed instead of stacking into one phone-width strip.",
      "refined the home screen, receipts, and expense forms to spread into roomy multi-column layouts on wide screens — no more thin column marooned in the middle of an empty page.",
      "added 'merge receipts' — select any quick splits from the receipts tab and fold them into a trip, either brand-new or an existing one, so you send a single link instead of chasing everyone across separate splits.",
      "added a member resolver for merges: when the same person shows up under different names (like 'jo' and 'jonathan'), merge them into one — or split apart anyone grouped by mistake.",
      "refined merging so the original receipts move into the trip (leaving the receipts list) and shared amounts sum up correctly when two people turn out to be one.",
    ],
  },
  {
    version: "2.5",
    date: "jul 1, 2026",
    title: "add to home screen 📲",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "added a custom install prompt so you can pop nest onto your home screen for a full-screen, app-like experience, straight from the browser.",
      "added a native one-tap install on android chrome & desktop chrome/edge, driven by our own on-brand modal.",
      "added tailored 'add to home screen' instructions for ios safari, which has no native install button.",
      "refined the prompt to only appear on platforms where installing actually works, and to stay quiet once you install or dismiss it.",
    ],
  },
  {
    version: "2.4.6",
    date: "may 7, 2026",
    title: "ledger details, everywhere 🔍",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "refined detailed ledger to show full receipt breakdown for settled items, no more disappearing details once a debt is paid.",
      "refined ledger interaction: tap any item to expand its breakdown, replacing the all-or-nothing summary toggle.",
      "refined share fractions to use a unified pill style across detailed ledger, expense card breakdowns, and the receipt page.",
      "fixed duplicate names appearing in receipt item assignments when one person had multiple shares.",
    ],
  },
  {
    version: "2.4.5",
    date: "may 7, 2026",
    title: "tap to dismiss 👆",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "fixed 'how nest works' info modal so tapping the backdrop dismisses it, matching the rest of the app.",
    ],
  },
  {
    version: "2.4.4",
    date: "may 7, 2026",
    title: "summary mode 📋",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added 'summary' and 'full receipt' toggle inside the detailed ledger, switch per-member to scan totals or audit every line.",
      "refined compact ledger rows with tighter padding and font for at-a-glance scanning.",
    ],
  },
  {
    version: "2.4.3",
    date: "may 4, 2026",
    title: "receipt-grade ledger 🧾",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "refined detailed ledger with receipt-style breakdowns.",
      "refined money format, correctly display the currency on each amount",
      "added multi-payer section a proportion bar showing each payer's share at a glance.",
    ],
  },
  {
    version: "2.4.2",
    date: "apr 30, 2026",
    title: "add not found 🛡️",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: ["added not found page.", "refined opengraph image."],
  },
  {
    version: "2.4.1",
    date: "apr 30, 2026",
    title: "global emoji push 🍃",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added emoji assets using twemoji.",
      "added new app icon and opengraph using global emoji.",
    ],
  },
  {
    version: "2.4",
    date: "apr 30, 2026",
    title: "identities & pwa polish 🐣",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "added a custom 1200x630 opengraph image for dynamic spatial ui previews on social share.",
      "added native apple-touch-icon support directly in the app directory for perfectly crisp ios home screen icons.",
      "refined full pwa asset pipeline with 192px and 512px icons for native android and chrome installation.",
    ],
  },
  {
    version: "2.3.2",
    date: "apr 29, 2026",
    title: "nicknames ✨",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added nicknames. pick how you want to be seen across nest, separate from your google account name.",
      "refined trip ownership labels to use your nickname automatically when you change it.",
      "refined quick split creation to seed the first member from your nickname instead of your google name.",
    ],
  },
  {
    version: "2.3.1",
    date: "apr 29, 2026",
    title: "snapshots & sharing polish 📸",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added trip snapshots, high-res exportable postcard that generates instantly when you share a trip.",
      "refined the receipt export to beautifully display multiple payers side-by-side with exact amounts.",
    ],
  },
  {
    version: "2.3",
    date: "apr 29, 2026",
    title: "the real receipt & bulletproof math update 🧾",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "refined the exportable receipt, featuring a master order list and exact, per-person tax & tip slices.",
      "refined settlement engine to handle multi-payer scenarios, distributing credit perfectly proportional to what was paid.",
      "refined quick-splits, securely filtered at the database level before they ever reach your device.",
      "refined codebase, centralizing all date and currency logic and setting the stage for a true native app wrap.",
      "fixed 'penny drift' bug so exact-split receipts stay perfectly balanced, no matter how many times you edit them.",
    ],
  },
  {
    version: "2.2.3",
    date: "apr 22, 2026",
    title: "relentless guard & quick split security 🛡️",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "fixed the version guard to use relative paths and cache-busting URLs to guarantee users always get the freshest update.",
      "fixed quick split sharing so your friends can view the beautiful receipt link without being forced to create an account.",
      "fixed 'edit receipt' button on quick splits, prevent it appearing on non owner user.",
    ],
  },
  {
    version: "2.2.2",
    date: "apr 16, 2026",
    title: "the always fresh update 🍃",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "fixed service worker caching that was trapping users on old versions of the app.",
      "added a smart 'version guard' that detects new updates, silently assassinates the old cache, and automatically refreshes the app.",
      "added an automated build script to sync version numbers safely.",
      "added offline screen using modern react hooks to gracefully pause the app and prevent unsyncable changes.",
    ],
  },
  {
    version: "2.2.1",
    date: "apr 16, 2026",
    title: "smart routing & modal polish 🧠",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added a 'smart back button' on trip pages that knows if you came from a shared link or the dashboard, preventing users from getting stuck.",
      "added clickable background backdrops to all modals.",
      "added exception for expense detail page, allowing the page shared to a non-logged in user",
    ],
  },
  {
    version: "2.2",
    date: "apr 16, 2026",
    title: "settlements & polish update 🤝",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "added a native 'share the proof' button inside settlements so you can paste the exact math directly into your group chat.",
      "added native ios/android share sheets to both trip pages and quick split receipts.",
      "added safe-area-inset padding so the bottom nav bar perfectly respects phone bezels.",
      "refined the 'who pays who' section. user now can verify their own tab, reveals exactly what was consumed vs paid.",
      "fixed dashboard filters not persist when you hit the back button, now saved via params.",
      "fixed a math display bug where exact split items now properly show their fractions in expense detail page (e.g., french fries (1/2)).",
    ],
  },
  {
    version: "2.1.1",
    date: "apr 15, 2026",
    title: "receipts bug fix & tab sync 🛠️",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "fixed receipts tab filter bug.",
      "fixed a routing bug in switching between trips and receipts.",
      "added search and sorting filters directly to the receipts tab.",
    ],
  },
  {
    version: "2.1",
    date: "apr 15, 2026",
    title: "quick splits 📸",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "added 'quick split': standalone receipts without needing a full group trip.",
      "refine home dashboard with dedicated tabs for trips and quick receipts.",
      "refine about modal and social links",
      "refine changelog layout",
    ],
  },
  {
    version: "2.0.1",
    date: "apr 15, 2026",
    title: "refined navigation & rich cards ✨",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added a clean bottom app bar.",
      "refine profile menu into a sleek, full-screen bottom sheet modal.",
    ],
  },
  {
    version: "2.0",
    date: "apr 13, 2026",
    title: "receipts & borders 🌍",
    badge: "major",
    badgeColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    features: [
      "added smart multi-currency support with dynamic decimal formatting.",
      "added exportable, high-res, nest-branded receipt images for easy sharing.",
      "fixed the date picker with year navigation and a 'right now' shortcut.",
      "fixed a navigation loop bug when exiting trips.",
    ],
  },
  {
    version: "1.2.3",
    date: "apr 2, 2026",
    title: "cleaning up 🧼",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "refine code-base structure",
      "refine changelog ui, separate static imports.",
    ],
  },
  {
    version: "1.2.2",
    date: "apr 2, 2026",
    title: "small changes 😊",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: ["fix info icon size inconsistency."],
  },
  {
    version: "1.2.1",
    date: "apr 2, 2026",
    title: "crew management & prompt fix 👥",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added rename members feature.",
      "refine the member management into a dedicated popup modal.",
      "fix the receipt scanner prompt to strictly output exact category matches.",
    ],
  },
  {
    version: "1.2",
    date: "mar 31, 2026",
    title: "math & polish 💅",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "added a dedicated in-app changelog page.",
      "added transparent breakdowns for custom adjustments in the detailed ledger.",
      "refine the about screen with new social buttons.",
      "fixed a 'phantom tax' math bug for weighted item splits.",
      "fixed some price ui alignment across the board to snap cleanly to the right edge.",
    ],
  },
  {
    version: "1.1",
    date: "mar 31, 2026",
    title: "receipts & ledgers ✨",
    badge: "feature",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    features: [
      "added new receipt scanning logic to handle specific item discounts.",
      "added logic to isolate individual item discounts from global tax and discount math.",
      "added individual item prices directly inside the detailed ledger section.",
      "added transparent item breakdowns associated with each member in the expense list.",
    ],
  },
  {
    version: "1.0.1",
    date: "mar 31, 2026",
    title: "bug fixing 🐛",
    badge: "patch",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    features: [
      "added a shiny new about screen with creator social links.",
      "fixed a buggy bouncing arrow on the home screen empty state.",
      "fixed an issue where the about screen wouldn't show when a trip was empty.",
    ],
  },
  {
    version: "1.0",
    date: "mar 31, 2026",
    title: "the beginning 🐣",
    badge: "launch",
    badgeColor: "bg-amber-100 text-amber-700 border-amber-200",
    features: [
      "launched 'nest.' into the wild!",
      "receipt scanning with gemini!",
      "exact splitting, equal splitting, and custom adjustments.",
      "smart debt optimization (who pays who).",
      "beautiful, transparent ledger breakdowns.",
    ],
  },
];
